# Makefile

# Compiler
CC = g++

# Output binary name
TARGET = bst

# Source file(s)
SRC = bst.cpp

# Build rule
$(TARGET): $(SRC)
	$(CC) -o $(TARGET) $(SRC)

# Clean rule to remove the compiled binary
clean:
	rm -f $(TARGET)

